const admin = require('firebase-admin');

function initAdmin() {
  if (admin.apps && admin.apps.length) return admin;
  if (process.env.FIREBASE_SERVICE_ACCOUNT) {
    try {
      const svc = JSON.parse(process.env.FIREBASE_SERVICE_ACCOUNT);
      admin.initializeApp({ credential: admin.credential.cert(svc) });
      return admin;
    } catch (e) {
      console.error('Failed to parse FIREBASE_SERVICE_ACCOUNT', e);
    }
  }
  // fallback to default credentials (e.g., GOOGLE_APPLICATION_CREDENTIALS)
  admin.initializeApp();
  return admin;
}

const a = initAdmin();
const db = a.firestore();

// Default password for created users (can be overridden by client)
const DEFAULT_PASSWORD = process.env.DEFAULT_USER_PASSWORD || '12345678';

export default async function handler(req, res) {
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });

  const { users } = req.body || {};
  if (!Array.isArray(users) || users.length === 0) {
    return res.status(400).json({ error: 'No users provided' });
  }

  const results = [];

  for (let i = 0; i < users.length; i++) {
    const row = users[i] || {};
    const name = (row.name || '').toString();
    const email = (row.email || row.mail || row['mail id'] || '').toString().trim();
    if (!email) {
      results.push({ index: i, ok: false, error: 'missing email' });
      continue;
    }

    try {
      // try to create auth user; if exists, fetch existing
      let userRecord;
      try {
        userRecord = await a.auth().createUser({ email, password: DEFAULT_PASSWORD, displayName: name || undefined });
      } catch (err) {
        if (err.code === 'auth/email-already-exists' || err.code === 'auth/user-not-found') {
          // fetch existing
          try {
            userRecord = await a.auth().getUserByEmail(email);
          } catch (e) {
            console.warn('Failed to get existing user:', e.message || e);
            userRecord = null;
          }
        } else {
          throw err;
        }
      }

      const uid = userRecord ? userRecord.uid : undefined;
      if (!uid) {
        // create a Firestore-only user doc with autogenerated id
        const docRef = await db.collection('users').add({ name: name || '', email, role: 'employee', createdAt: a.firestore.FieldValue.serverTimestamp() });
        results.push({ index: i, ok: true, uid: docRef.id, createdAuth: false });
      } else {
        // set user doc with uid
        await db.collection('users').doc(uid).set({ uid, name: name || '', email, role: 'employee', createdAt: a.firestore.FieldValue.serverTimestamp() }, { merge: true });
        results.push({ index: i, ok: true, uid, createdAuth: true });
      }
    } catch (err) {
      console.error('bulkUsers: row error', err);
      results.push({ index: i, ok: false, error: err.message || String(err) });
    }
  }

  return res.status(200).json({ results, count: results.filter(r => r.ok).length });
}
